/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Both: typeof import('./src/components/info_page/both.vue')['default']
    ChartComponent: typeof import('./src/components/dietitian_page/ChartComponent.vue')['default']
    ChatBox: typeof import('./src/components/Programming_dev_1/chatBox.vue')['default']
    CodeBox: typeof import('./src/components/Programming_dev_1/codeBox.vue')['default']
    DialogBox: typeof import('./src/components/version1/dialogBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Gather: typeof import('./src/components/home_page/gather.vue')['default']
    Gatherf: typeof import('./src/components/feedback_page/gatherf.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home1: typeof import('./src/components/home_page/home1.vue')['default']
    IconBehindInputBox: typeof import('./src/components/Programming_dev_1/IconBehindInputBox.vue')['default']
    Info1: typeof import('./src/components/info_page/info1.vue')['default']
    InitialMode: typeof import('./src/components/Programming_dev_1/InitialMode.vue')['default']
    InputBox: typeof import('./src/components/Programming_dev_1/InputBox.vue')['default']
    Main: typeof import('./src/components/version1/main.vue')['default']
    Main_container: typeof import('./src/components/version1/main_container.vue')['default']
    Mainf: typeof import('./src/components/feedback_page/mainf.vue')['default']
    PageWithoutSidebar: typeof import('./src/components/Programming_dev_1/pageWithoutSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting_gather: typeof import('./src/components/setting_page/setting_gather.vue')['default']
    Setting_main: typeof import('./src/components/setting_page/setting_main.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Test: typeof import('./src/components/version1/test.vue')['default']
    WholeInputBox: typeof import('./src/components/Programming_dev_1/WholeInputBox.vue')['default']
  }
}
